eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/
  instance:
      prefer-ip-address: true
spring:
  application:
    name: config
  rabbitmq:
    host:
    port:
    username:
    password:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xuexiaoao/config-repo.git
          username:
          password: 
          basedir: C:\workspace\basedir
management:
  endpoints:
    web:
      exposure:
        include: "*"